/*
 * This file is generated by jOOQ.
 */
package com.spaceship.crm.jooq;


import com.spaceship.crm.jooq.tables.Activity;
import com.spaceship.crm.jooq.tables.Dream;
import com.spaceship.crm.jooq.tables.Role;
import com.spaceship.crm.jooq.tables.UserActivity;
import com.spaceship.crm.jooq.tables.UserInfo;
import com.spaceship.crm.jooq.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACTIVITY_PKEY = Indexes0.ACTIVITY_PKEY;
    public static final Index IDXCHN68HOQYOUNT8VQ94YSX4RL5 = Indexes0.IDXCHN68HOQYOUNT8VQ94YSX4RL5;
    public static final Index DREAM_PKEY = Indexes0.DREAM_PKEY;
    public static final Index ROLE_PKEY = Indexes0.ROLE_PKEY;
    public static final Index USER_ACTIVITY_PKEY = Indexes0.USER_ACTIVITY_PKEY;
    public static final Index USER_INFO_PKEY = Indexes0.USER_INFO_PKEY;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;
    public static final Index USERS_USERNAME_C = Indexes0.USERS_USERNAME_C;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACTIVITY_PKEY = Internal.createIndex("activity_pkey", Activity.ACTIVITY, new OrderField[] { Activity.ACTIVITY.ID }, true);
        public static Index IDXCHN68HOQYOUNT8VQ94YSX4RL5 = Internal.createIndex("idxchn68hoqyount8vq94ysx4rl5", Activity.ACTIVITY, new OrderField[] { Activity.ACTIVITY.NAME }, false);
        public static Index DREAM_PKEY = Internal.createIndex("dream_pkey", Dream.DREAM, new OrderField[] { Dream.DREAM.ID }, true);
        public static Index ROLE_PKEY = Internal.createIndex("role_pkey", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index USER_ACTIVITY_PKEY = Internal.createIndex("user_activity_pkey", UserActivity.USER_ACTIVITY, new OrderField[] { UserActivity.USER_ACTIVITY.ACTIVITY_ID, UserActivity.USER_ACTIVITY.USER_ID }, true);
        public static Index USER_INFO_PKEY = Internal.createIndex("user_info_pkey", UserInfo.USER_INFO, new OrderField[] { UserInfo.USER_INFO.ID }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USERS_USERNAME_C = Internal.createIndex("users_username_c", Users.USERS, new OrderField[] { Users.USERS.USERNAME }, true);
    }
}
