/*
 * This file is generated by jOOQ.
 */
package com.spaceship.crm.jooq;


import com.spaceship.crm.jooq.tables.Activity;
import com.spaceship.crm.jooq.tables.Dream;
import com.spaceship.crm.jooq.tables.Role;
import com.spaceship.crm.jooq.tables.UserActivity;
import com.spaceship.crm.jooq.tables.UserInfo;
import com.spaceship.crm.jooq.tables.UserRole;
import com.spaceship.crm.jooq.tables.Users;
import com.spaceship.crm.jooq.tables.records.ActivityRecord;
import com.spaceship.crm.jooq.tables.records.DreamRecord;
import com.spaceship.crm.jooq.tables.records.RoleRecord;
import com.spaceship.crm.jooq.tables.records.UserActivityRecord;
import com.spaceship.crm.jooq.tables.records.UserInfoRecord;
import com.spaceship.crm.jooq.tables.records.UserRoleRecord;
import com.spaceship.crm.jooq.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ActivityRecord> ACTIVITY_PKEY = UniqueKeys0.ACTIVITY_PKEY;
    public static final UniqueKey<DreamRecord> DREAM_PKEY = UniqueKeys0.DREAM_PKEY;
    public static final UniqueKey<RoleRecord> ROLE_PKEY = UniqueKeys0.ROLE_PKEY;
    public static final UniqueKey<UserActivityRecord> USER_ACTIVITY_PKEY = UniqueKeys0.USER_ACTIVITY_PKEY;
    public static final UniqueKey<UserInfoRecord> USER_INFO_PKEY = UniqueKeys0.USER_INFO_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;
    public static final UniqueKey<UsersRecord> USERS_USERNAME_C = UniqueKeys0.USERS_USERNAME_C;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DreamRecord, UsersRecord> DREAM__FK30303R9AFE6J46R1D81DP4RBY = ForeignKeys0.DREAM__FK30303R9AFE6J46R1D81DP4RBY;
    public static final ForeignKey<UserActivityRecord, ActivityRecord> USER_ACTIVITY__FKLW9O1XB2KI2HNWQ1O3KK5DLJA = ForeignKeys0.USER_ACTIVITY__FKLW9O1XB2KI2HNWQ1O3KK5DLJA;
    public static final ForeignKey<UserActivityRecord, UsersRecord> USER_ACTIVITY__FKS41IS1RAA3F0Y5Q5G0PW2RFD4 = ForeignKeys0.USER_ACTIVITY__FKS41IS1RAA3F0Y5Q5G0PW2RFD4;
    public static final ForeignKey<UserInfoRecord, UsersRecord> USER_INFO__FKR1B96CA4ASUVRHWOQKDMBO7NJ = ForeignKeys0.USER_INFO__FKR1B96CA4ASUVRHWOQKDMBO7NJ;
    public static final ForeignKey<UserRoleRecord, UsersRecord> USER_ROLE__FKJ345GK1BOVQVFAME88RCX7YYX = ForeignKeys0.USER_ROLE__FKJ345GK1BOVQVFAME88RCX7YYX;
    public static final ForeignKey<UserRoleRecord, RoleRecord> USER_ROLE__FKA68196081FVOVJHKEK5M97N3Y = ForeignKeys0.USER_ROLE__FKA68196081FVOVJHKEK5M97N3Y;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<ActivityRecord> ACTIVITY_PKEY = Internal.createUniqueKey(Activity.ACTIVITY, "activity_pkey", Activity.ACTIVITY.ID);
        public static final UniqueKey<DreamRecord> DREAM_PKEY = Internal.createUniqueKey(Dream.DREAM, "dream_pkey", Dream.DREAM.ID);
        public static final UniqueKey<RoleRecord> ROLE_PKEY = Internal.createUniqueKey(Role.ROLE, "role_pkey", Role.ROLE.ID);
        public static final UniqueKey<UserActivityRecord> USER_ACTIVITY_PKEY = Internal.createUniqueKey(UserActivity.USER_ACTIVITY, "user_activity_pkey", UserActivity.USER_ACTIVITY.ACTIVITY_ID, UserActivity.USER_ACTIVITY.USER_ID);
        public static final UniqueKey<UserInfoRecord> USER_INFO_PKEY = Internal.createUniqueKey(UserInfo.USER_INFO, "user_info_pkey", UserInfo.USER_INFO.ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> USERS_USERNAME_C = Internal.createUniqueKey(Users.USERS, "users_username_c", Users.USERS.USERNAME);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<DreamRecord, UsersRecord> DREAM__FK30303R9AFE6J46R1D81DP4RBY = Internal.createForeignKey(com.spaceship.crm.jooq.Keys.USERS_PKEY, Dream.DREAM, "dream__fk30303r9afe6j46r1d81dp4rby", Dream.DREAM.USER_ID);
        public static final ForeignKey<UserActivityRecord, ActivityRecord> USER_ACTIVITY__FKLW9O1XB2KI2HNWQ1O3KK5DLJA = Internal.createForeignKey(com.spaceship.crm.jooq.Keys.ACTIVITY_PKEY, UserActivity.USER_ACTIVITY, "user_activity__fklw9o1xb2ki2hnwq1o3kk5dlja", UserActivity.USER_ACTIVITY.ACTIVITY_ID);
        public static final ForeignKey<UserActivityRecord, UsersRecord> USER_ACTIVITY__FKS41IS1RAA3F0Y5Q5G0PW2RFD4 = Internal.createForeignKey(com.spaceship.crm.jooq.Keys.USERS_PKEY, UserActivity.USER_ACTIVITY, "user_activity__fks41is1raa3f0y5q5g0pw2rfd4", UserActivity.USER_ACTIVITY.USER_ID);
        public static final ForeignKey<UserInfoRecord, UsersRecord> USER_INFO__FKR1B96CA4ASUVRHWOQKDMBO7NJ = Internal.createForeignKey(com.spaceship.crm.jooq.Keys.USERS_PKEY, UserInfo.USER_INFO, "user_info__fkr1b96ca4asuvrhwoqkdmbo7nj", UserInfo.USER_INFO.USER_ID);
        public static final ForeignKey<UserRoleRecord, UsersRecord> USER_ROLE__FKJ345GK1BOVQVFAME88RCX7YYX = Internal.createForeignKey(com.spaceship.crm.jooq.Keys.USERS_PKEY, UserRole.USER_ROLE, "user_role__fkj345gk1bovqvfame88rcx7yyx", UserRole.USER_ROLE.USER_ID);
        public static final ForeignKey<UserRoleRecord, RoleRecord> USER_ROLE__FKA68196081FVOVJHKEK5M97N3Y = Internal.createForeignKey(com.spaceship.crm.jooq.Keys.ROLE_PKEY, UserRole.USER_ROLE, "user_role__fka68196081fvovjhkek5m97n3y", UserRole.USER_ROLE.ROLE_ID);
    }
}
