/*
 * This file is generated by jOOQ.
 */
package com.spaceship.crm.jooq.tables.records;


import com.spaceship.crm.jooq.tables.Activity;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityRecord extends UpdatableRecordImpl<ActivityRecord> implements Record4<Long, Timestamp, String, Timestamp> {

    private static final long serialVersionUID = 1567768992;

    /**
     * Setter for <code>public.activity.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.activity.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.activity.end_date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.activity.end_date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.activity.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.activity.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.activity.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.activity.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Timestamp, String, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Timestamp, String, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Activity.ACTIVITY.ID;
    }

    @Override
    public Field<Timestamp> field2() {
        return Activity.ACTIVITY.END_DATE;
    }

    @Override
    public Field<String> field3() {
        return Activity.ACTIVITY.NAME;
    }

    @Override
    public Field<Timestamp> field4() {
        return Activity.ACTIVITY.START_DATE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Timestamp component2() {
        return getEndDate();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Timestamp component4() {
        return getStartDate();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Timestamp value2() {
        return getEndDate();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Timestamp value4() {
        return getStartDate();
    }

    @Override
    public ActivityRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ActivityRecord value2(Timestamp value) {
        setEndDate(value);
        return this;
    }

    @Override
    public ActivityRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ActivityRecord value4(Timestamp value) {
        setStartDate(value);
        return this;
    }

    @Override
    public ActivityRecord values(Long value1, Timestamp value2, String value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityRecord
     */
    public ActivityRecord() {
        super(Activity.ACTIVITY);
    }

    /**
     * Create a detached, initialised ActivityRecord
     */
    public ActivityRecord(Long id, Timestamp endDate, String name, Timestamp startDate) {
        super(Activity.ACTIVITY);

        set(0, id);
        set(1, endDate);
        set(2, name);
        set(3, startDate);
    }
}
