/*
 * This file is generated by jOOQ.
 */
package com.spaceship.crm.jooq.tables.records;


import com.spaceship.crm.jooq.tables.UserActivity;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserActivityRecord extends UpdatableRecordImpl<UserActivityRecord> implements Record4<Timestamp, Long, Long, Long> {

    private static final long serialVersionUID = -1940227657;

    /**
     * Setter for <code>public.user_activity.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_activity.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>public.user_activity.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_activity.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.user_activity.activity_id</code>.
     */
    public void setActivityId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_activity.activity_id</code>.
     */
    public Long getActivityId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.user_activity.user_id</code>.
     */
    public void setUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_activity.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Timestamp, Long, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Timestamp, Long, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Timestamp> field1() {
        return UserActivity.USER_ACTIVITY.CREATED_AT;
    }

    @Override
    public Field<Long> field2() {
        return UserActivity.USER_ACTIVITY.CREATED_BY;
    }

    @Override
    public Field<Long> field3() {
        return UserActivity.USER_ACTIVITY.ACTIVITY_ID;
    }

    @Override
    public Field<Long> field4() {
        return UserActivity.USER_ACTIVITY.USER_ID;
    }

    @Override
    public Timestamp component1() {
        return getCreatedAt();
    }

    @Override
    public Long component2() {
        return getCreatedBy();
    }

    @Override
    public Long component3() {
        return getActivityId();
    }

    @Override
    public Long component4() {
        return getUserId();
    }

    @Override
    public Timestamp value1() {
        return getCreatedAt();
    }

    @Override
    public Long value2() {
        return getCreatedBy();
    }

    @Override
    public Long value3() {
        return getActivityId();
    }

    @Override
    public Long value4() {
        return getUserId();
    }

    @Override
    public UserActivityRecord value1(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserActivityRecord value2(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public UserActivityRecord value3(Long value) {
        setActivityId(value);
        return this;
    }

    @Override
    public UserActivityRecord value4(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserActivityRecord values(Timestamp value1, Long value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserActivityRecord
     */
    public UserActivityRecord() {
        super(UserActivity.USER_ACTIVITY);
    }

    /**
     * Create a detached, initialised UserActivityRecord
     */
    public UserActivityRecord(Timestamp createdAt, Long createdBy, Long activityId, Long userId) {
        super(UserActivity.USER_ACTIVITY);

        set(0, createdAt);
        set(1, createdBy);
        set(2, activityId);
        set(3, userId);
    }
}
