/*
 * This file is generated by jOOQ.
 */
package com.spaceship.crm.jooq.tables;


import com.spaceship.crm.jooq.Indexes;
import com.spaceship.crm.jooq.Keys;
import com.spaceship.crm.jooq.Public;
import com.spaceship.crm.jooq.tables.records.UserActivityRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserActivity extends TableImpl<UserActivityRecord> {

    private static final long serialVersionUID = 1208070366;

    /**
     * The reference instance of <code>public.user_activity</code>
     */
    public static final UserActivity USER_ACTIVITY = new UserActivity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserActivityRecord> getRecordType() {
        return UserActivityRecord.class;
    }

    /**
     * The column <code>public.user_activity.created_at</code>.
     */
    public final TableField<UserActivityRecord, Timestamp> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.user_activity.created_by</code>.
     */
    public final TableField<UserActivityRecord, Long> CREATED_BY = createField(DSL.name("created_by"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.user_activity.activity_id</code>.
     */
    public final TableField<UserActivityRecord, Long> ACTIVITY_ID = createField(DSL.name("activity_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_activity.user_id</code>.
     */
    public final TableField<UserActivityRecord, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.user_activity</code> table reference
     */
    public UserActivity() {
        this(DSL.name("user_activity"), null);
    }

    /**
     * Create an aliased <code>public.user_activity</code> table reference
     */
    public UserActivity(String alias) {
        this(DSL.name(alias), USER_ACTIVITY);
    }

    /**
     * Create an aliased <code>public.user_activity</code> table reference
     */
    public UserActivity(Name alias) {
        this(alias, USER_ACTIVITY);
    }

    private UserActivity(Name alias, Table<UserActivityRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserActivity(Name alias, Table<UserActivityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserActivity(Table<O> child, ForeignKey<O, UserActivityRecord> key) {
        super(child, key, USER_ACTIVITY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_ACTIVITY_PKEY);
    }

    @Override
    public UniqueKey<UserActivityRecord> getPrimaryKey() {
        return Keys.USER_ACTIVITY_PKEY;
    }

    @Override
    public List<UniqueKey<UserActivityRecord>> getKeys() {
        return Arrays.<UniqueKey<UserActivityRecord>>asList(Keys.USER_ACTIVITY_PKEY);
    }

    @Override
    public List<ForeignKey<UserActivityRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserActivityRecord, ?>>asList(Keys.USER_ACTIVITY__FKLW9O1XB2KI2HNWQ1O3KK5DLJA, Keys.USER_ACTIVITY__FKS41IS1RAA3F0Y5Q5G0PW2RFD4);
    }

    public Activity activity() {
        return new Activity(this, Keys.USER_ACTIVITY__FKLW9O1XB2KI2HNWQ1O3KK5DLJA);
    }

    public Users users() {
        return new Users(this, Keys.USER_ACTIVITY__FKS41IS1RAA3F0Y5Q5G0PW2RFD4);
    }

    @Override
    public UserActivity as(String alias) {
        return new UserActivity(DSL.name(alias), this);
    }

    @Override
    public UserActivity as(Name alias) {
        return new UserActivity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserActivity rename(String name) {
        return new UserActivity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserActivity rename(Name name) {
        return new UserActivity(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Timestamp, Long, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
